/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.controlador.CategoriaController;
import gt.guatemarket.sistema.ventas.modelo.Categoria;
import gt.guatemarket.sistema.ventas.dao.CategoriaDAO;
import gt.guatemarket.sistema.ventas.dao.CategoriaDAOImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author omary
 */
public class FrmCategorias extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form FrmCategorias
     */
    public FrmCategorias() {
        initComponents();
        modelo = (DefaultTableModel) tablaCategorias.getModel();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreCategoria = new javax.swing.JTextField();
        agregarCategoria = new javax.swing.JButton();
        eliminarCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Categorias");

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre Categoria:");

        agregarCategoria.setText("Agregar Categoria");
        agregarCategoria.addActionListener(this::agregarCategoriaActionPerformed);

        eliminarCategoria.setText("Eliminar Categoria");

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre Categoria"
            }
        ));
        jScrollPane1.setViewportView(tablaCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarCategoria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCategoria)
                    .addComponent(eliminarCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCategorias() {
        modelo.setRowCount(0);

        CategoriaDAO dao = new CategoriaDAOImpl();

        List<Categoria> categorias = dao.listar();

        for (Categoria categoria : categorias) {

            modelo.addRow(new Object[]{
                categoria.getIdCategoria(),
                categoria.getNombreCategoria()
            });
        }
    }

    private void agregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCategoriaActionPerformed
        String codigo = idCategoria.getText().trim();
        String nombre = nombreCategoria.getText().trim();

        if (codigo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe completar todos los datos de la categoría.",
                    "Datos Incompletos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            Categoria nuevaCategoria = new Categoria();

            nuevaCategoria.setIdCategoria(codigo);
            nuevaCategoria.setNombreCategoria(nombre);

            CategoriaDAO dao = new CategoriaDAOImpl();
            dao.guardar(nuevaCategoria);

            cargarCategorias();

            JOptionPane.showMessageDialog(
                    this,
                    "Categoría guardada correctamente."
            );

            idCategoria.setText("");
            nombreCategoria.setText("");
            idCategoria.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar la categoría: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_agregarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCategoria;
    private javax.swing.JButton eliminarCategoria;
    private javax.swing.JTextField idCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCategoria;
    private javax.swing.JTable tablaCategorias;
    // End of variables declaration//GEN-END:variables
}
