/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.config.ConexionBD;
import gt.guatemarket.sistema.ventas.modelo.Despachos;
import gt.guatemarket.sistema.ventas.dao.DespachosDAO;
import gt.guatemarket.sistema.ventas.dao.DespachosDAOImpl;
import gt.guatemarket.sistema.ventas.dao.ProductoDAO;
import gt.guatemarket.sistema.ventas.dao.ProductoDAOImpl;
import gt.guatemarket.sistema.ventas.dao.FacturaDAO;
import gt.guatemarket.sistema.ventas.dao.FacturaDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.Factura;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Jonathan Chile
 */
public class FrmDespacho extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDespacho
     */
    public FrmDespacho() {
        initComponents();

        cargarMensajeros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        despachos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estadoDespacho = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        confirmarDespacho = new javax.swing.JButton();
        nitCliente = new javax.swing.JTextField();
        idVenta = new javax.swing.JTextField();
        buscarVenta = new javax.swing.JButton();
        generarFactura = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Despacho");

        despachos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre Producto", "Stocks Solicitados", "Stocks Disponibles", "Verificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(despachos);

        jLabel2.setText("ID Venta:");

        jLabel3.setText("Nit:");

        jLabel4.setText("Estado Despacho:");

        estadoDespacho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completado" }));
        estadoDespacho.addActionListener(this::estadoDespachoActionPerformed);

        jLabel6.setText("Repartidor:");

        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        confirmarDespacho.setText("Confirmar despacho");
        confirmarDespacho.addActionListener(this::confirmarDespachoActionPerformed);

        buscarVenta.setText("Buscar");
        buscarVenta.addActionListener(this::buscarVentaActionPerformed);

        generarFactura.setText("Generar Factura");
        generarFactura.addActionListener(this::generarFacturaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nitCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(idVenta)))
                            .addComponent(buscarVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 189, Short.MAX_VALUE)
                            .addComponent(estadoDespacho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(374, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generarFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmarDespacho))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarVenta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarDespacho)
                    .addComponent(generarFactura))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMensajeros() {
        jComboBox2.removeAllItems();
        String sql = "SELECT nombreEmpleado " + "FROM empleados " + "WHERE areaLaboral = 'Mensajero' " + "AND estadoEmpleado = 'Activo'";
        try (Connection cn = ConexionBD.conectar(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("nombreEmpleado"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar mensajeros:\n" + e.getMessage());
        }
    }

    private void estadoDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoDespachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoDespachoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void buscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVentaActionPerformed
        String venta = idVenta.getText().trim();
        if (venta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de venta.");
            return;
        }
        String sqlEstado = "SELECT estadoDespacho " + "FROM despachos " + "WHERE idVenta = ? " + "AND estadoDespacho = 'Completado'";
        try (Connection cn = ConexionBD.conectar(); PreparedStatement ps = cn.prepareStatement(sqlEstado)) {
            ps.setString(1, venta);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Esta venta ya fue despachada.", "Venta ya despachada", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al verificar el despacho:\n" + e.getMessage());
            return;
        }
        String sql = "SELECT v.nitCliente, " + "d.idProducto, d.nombreProducto, " + "d.cantidadProducto, p.stockproducto " + "FROM ventas v " + "INNER JOIN detalle_venta d ON v.idVenta = d.idVenta " + "INNER JOIN inventario_productos p " + "ON d.idProducto = p.idproducto " + "WHERE v.idVenta = ?";
        try (Connection cn = ConexionBD.conectar(); PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, venta);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) despachos.getModel();
            modelo.setRowCount(0);
            boolean encontrado = false;
            while (rs.next()) {
                encontrado = true;
                nitCliente.setText(rs.getString("nitCliente"));
                int cantidad = rs.getInt("cantidadProducto");
                int stock = rs.getInt("stockproducto");
                modelo.addRow(new Object[]{rs.getString("idProducto"), rs.getString("nombreProducto"), cantidad, stock, cantidad <= stock});
            }
            if (!encontrado) {
                nitCliente.setText("");
                JOptionPane.showMessageDialog(this, "No se encontró la venta.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar la venta:\n" + e.getMessage());
        }
    }//GEN-LAST:event_buscarVentaActionPerformed

    private void confirmarDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDespachoActionPerformed
        String venta = idVenta.getText().trim();
        if (venta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero busque una venta.");
            return;
        }
        if (despachos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay productos para despachar.");
            return;
        }
        boolean hayProductos = false;
        for (int i = 0; i < despachos.getRowCount(); i++) {
            boolean cumple = Boolean.TRUE.equals(despachos.getValueAt(i, 4));
            if (cumple) {
                hayProductos = true;
                break;
            }
        }
        if (!hayProductos) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un producto.");
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea confirmar la orden de despacho?", "Confirmar despacho", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        String estado = estadoDespacho.getSelectedItem().toString();
        Despachos orden = new Despachos();
        orden.setIdVenta(venta);
        orden.setFechaDespacho(java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        orden.setEstadoDespacho(estado);
        DespachosDAO dao = new DespachosDAOImpl();
        boolean guardado = dao.guardar(orden);
        if (!guardado) {
            return;
        }
        ProductoDAO productoDAO = new ProductoDAOImpl();
        for (int i = 0; i < despachos.getRowCount(); i++) {
            boolean cumple = Boolean.TRUE.equals(despachos.getValueAt(i, 4));
            if (!cumple) {
                continue;
            }
            String idProducto = despachos.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(despachos.getValueAt(i, 2).toString());
            boolean actualizado = productoDAO.descontarStock(idProducto, cantidad);
            if (!actualizado) {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el stock del producto: " + idProducto);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Orden de despacho guardada correctamente.");
        DefaultTableModel modelo = (DefaultTableModel) despachos.getModel();
        modelo.setRowCount(0);
        idVenta.setText("");
        nitCliente.setText("");
    }//GEN-LAST:event_confirmarDespachoActionPerformed

    private void generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFacturaActionPerformed
        String venta = idVenta.getText().trim();

        if (venta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la venta.");
            return;
        }

        String sql = "SELECT "
                + "v.idVenta AS idVenta, "
                + "v.nombreCliente AS nombreCliente, "
                + "v.nitCliente AS nitCliente, "
                + "v.telefonoCliente AS telefonoCliente, "
                + "v.correoCliente AS correoCliente, "
                + "v.fechaVenta AS fechaVenta, "
                + "d.nombreProducto AS nombreProducto, "
                + "d.cantidadProducto AS cantidadProducto, "
                + "d.precioUnitario AS precioUnitario, "
                + "(d.cantidadProducto * d.precioUnitario) AS total "
                + "FROM ventas v "
                + "INNER JOIN detalle_venta d "
                + "ON v.idVenta = d.idVenta "
                + "WHERE v.idVenta = ?";

        try {
            Connection cn = ConexionBD.conectar();
            PreparedStatement ps = cn.prepareStatement(sql);

            ps.setString(1, venta);

            ResultSet rs = ps.executeQuery();

            boolean encontrado = false;
            double totalFactura = 0;

            StringBuilder factura = new StringBuilder();

            factura.append("========================================\n");
            factura.append("              GUATEMARKET\n");
            factura.append("                 FACTURA\n");
            factura.append("========================================\n");

            while (rs.next()) {

                if (!encontrado) {
                    encontrado = true;

                    factura.append("ID Venta: ")
                            .append(rs.getString("idVenta"))
                            .append("\n");

                    factura.append("Cliente: ")
                            .append(rs.getString("nombreCliente"))
                            .append("\n");

                    factura.append("NIT: ")
                            .append(rs.getString("nitCliente"))
                            .append("\n");

                    factura.append("Telefono: ")
                            .append(rs.getString("telefonoCliente"))
                            .append("\n");

                    factura.append("Correo: ")
                            .append(rs.getString("correoCliente"))
                            .append("\n");

                    factura.append("Fecha: ")
                            .append(rs.getString("fechaVenta"))
                            .append("\n");

                    factura.append("----------------------------------------\n");
                    factura.append("Producto       Cant.       Precio\n");
                    factura.append("----------------------------------------\n");
                }

                String producto = rs.getString("nombreProducto");
                int cantidad = rs.getInt("cantidadProducto");
                double precio = rs.getDouble("precioUnitario");
                double total = rs.getDouble("total");

                totalFactura += total;

                factura.append(producto)
                        .append("       ")
                        .append(cantidad)
                        .append("       Q")
                        .append(String.format("%.2f", precio))
                        .append("\n");
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontró la venta.");
                return;
            }

            factura.append("----------------------------------------\n");
            factura.append("TOTAL: Q")
                    .append(String.format("%.2f", totalFactura))
                    .append("\n");

            factura.append("========================================\n");
            factura.append("          Gracias por su compra\n");
            factura.append("========================================");

            // GUARDAR FACTURA
            Factura nuevaFactura = new Factura();

            nuevaFactura.setIdVenta(venta);

            nuevaFactura.setFechaFactura(
                    java.time.LocalDateTime.now().format(
                            java.time.format.DateTimeFormatter.ofPattern(
                                    "yyyy-MM-dd HH:mm:ss"
                            )
                    )
            );

            nuevaFactura.setTotal(totalFactura);

            FacturaDAO dao = new FacturaDAOImpl();

            if (!dao.guardar(nuevaFactura)) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo guardar la factura."
                );
                return;
            }

            // MOSTRAR FACTURA
            JTextArea areaFactura = new JTextArea(
                    factura.toString()
            );

            areaFactura.setEditable(false);

            areaFactura.setFont(
                    new java.awt.Font(
                            "Monospaced",
                            java.awt.Font.PLAIN,
                            14
                    )
            );

            JScrollPane scroll = new JScrollPane(areaFactura);

            scroll.setPreferredSize(
                    new java.awt.Dimension(600, 450)
            );

            JOptionPane.showMessageDialog(
                    this,
                    scroll,
                    "Factura",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al generar la factura:\n"
                    + e.getMessage()
            );
        }
    }//GEN-LAST:event_generarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarVenta;
    private javax.swing.JButton confirmarDespacho;
    private javax.swing.JTable despachos;
    private javax.swing.JComboBox<String> estadoDespacho;
    private javax.swing.JButton generarFactura;
    private javax.swing.JTextField idVenta;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nitCliente;
    // End of variables declaration//GEN-END:variables
}
