/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.dao.EmpleadoDAO;
import gt.guatemarket.sistema.ventas.dao.EmpleadoDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.Empleado;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author omary
 */
public class FrmEmpleados extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        
        setTitle("Empleados");

        modelo = (DefaultTableModel) tablaEmpleados.getModel();
        cargarEmpleados();
        sorter = new TableRowSorter<>((DefaultTableModel) tablaEmpleados.getModel());
        tablaEmpleados.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoEmpleado = new javax.swing.JTextField();
        nombreEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        areaEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        estadoEmpleado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        empleadoBusqueda = new javax.swing.JTextField();
        agregarEmpleado = new javax.swing.JButton();
        editarEmpleado = new javax.swing.JButton();
        eliminarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Clientes");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Empleados:");

        jLabel1.setText("Codigo Empleado:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Area Laboral:");

        areaEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas", "Logistica", "Despacho", "Mensajero" }));

        jLabel4.setText("Estado:");

        estadoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Retirado" }));

        jLabel5.setText("🔍");

        empleadoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empleadoBusquedaKeyReleased(evt);
            }
        });

        agregarEmpleado.setText("Agregar");
        agregarEmpleado.addActionListener(this::agregarEmpleadoActionPerformed);

        editarEmpleado.setText("Editar");
        editarEmpleado.addActionListener(this::editarEmpleadoActionPerformed);

        eliminarEmpleado.setText("Eliminar");
        eliminarEmpleado.addActionListener(this::eliminarEmpleadoActionPerformed);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Empleado", "Nombre Empleado", "Area Laboral", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(codigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(agregarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarEmpleado)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(areaEmpleado, 0, 211, Short.MAX_VALUE)
                                    .addComponent(estadoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empleadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(areaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(estadoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empleadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarEmpleado)
                    .addComponent(editarEmpleado)
                    .addComponent(eliminarEmpleado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEmpleados() {
        modelo.setRowCount(0);
        EmpleadoDAO dao = new EmpleadoDAOImpl();
        List<Empleado> empleados = dao.listar();
        for (Empleado empleado : empleados) {
            modelo.addRow(new Object[]{empleado.getCodigoEmpleado(), empleado.getNombreEmpleado(), empleado.getAreaEmpleado(), empleado.getEstadoEmpleado()});
        }
    }

    private void agregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadoActionPerformed
        String codigo = codigoEmpleado.getText().trim();
        String nombre = nombreEmpleado.getText().trim();
        String area = areaEmpleado.getSelectedItem().toString();
        String estado = estadoEmpleado.getSelectedItem().toString();
        if (codigo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los datos del cliente.", "Datos Incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Empleado nuevoCliente = new Empleado(codigo, nombre, area, estado);
        EmpleadoDAO dao = new EmpleadoDAOImpl();
        dao.guardar(nuevoCliente);
        cargarEmpleados();
        JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.");
        codigoEmpleado.setText("");
        nombreEmpleado.setText("");
        areaEmpleado.setSelectedIndex(0);
        estadoEmpleado.setSelectedIndex(0);
        codigoEmpleado.requestFocus();
    }//GEN-LAST:event_agregarEmpleadoActionPerformed

    private void editarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoActionPerformed
        if (codigoEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla.");
            return;
        }
        String codigo = codigoEmpleado.getText();
        String nombre = nombreEmpleado.getText();
        String area = areaEmpleado.getSelectedItem().toString();
        String estado = estadoEmpleado.getSelectedItem().toString();
        Empleado empleado = new Empleado(codigo, nombre, area, estado);
        EmpleadoDAO dao = new EmpleadoDAOImpl();
        dao.actualizar(empleado);
        cargarEmpleados();
        JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
    }//GEN-LAST:event_editarEmpleadoActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        int fila = tablaEmpleados.getSelectedRow();
        if (fila != -1) {
            codigoEmpleado.setText(tablaEmpleados.getValueAt(fila, 0).toString());
            nombreEmpleado.setText(tablaEmpleados.getValueAt(fila, 1).toString());
            areaEmpleado.setSelectedItem(tablaEmpleados.getValueAt(fila, 2).toString());
            estadoEmpleado.setSelectedItem(tablaEmpleados.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void empleadoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleadoBusquedaKeyReleased
        String texto = empleadoBusqueda.getText();

        if (texto.trim().isEmpty()) {

            sorter.setRowFilter(null);

        } else {

            sorter.setRowFilter(
                    RowFilter.regexFilter("(?i)" + texto));
        }
    }//GEN-LAST:event_empleadoBusquedaKeyReleased

    private void eliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadoActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del empleado:");
        if (codigo == null || codigo.trim().isEmpty()) {
            return;
        }
        codigo = codigo.trim();
        EmpleadoDAO dao = new EmpleadoDAOImpl();
        Empleado empleado = dao.buscarPorCodigo(codigo);
        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "El empleado no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirmar = JOptionPane.showConfirmDialog(this, "Empleado: " + empleado.getNombreEmpleado() + "\n\n¿Desea eliminar este empleado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            if (dao.eliminar(codigo)) {
                cargarEmpleados();
                JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpleado;
    private javax.swing.JComboBox<String> areaEmpleado;
    private javax.swing.JTextField codigoEmpleado;
    private javax.swing.JButton editarEmpleado;
    private javax.swing.JButton eliminarEmpleado;
    private javax.swing.JTextField empleadoBusqueda;
    private javax.swing.JComboBox<String> estadoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
