/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.config.ConexionBD;

import gt.guatemarket.sistema.ventas.controlador.ClienteController;
import gt.guatemarket.sistema.ventas.modelo.Cliente;
import gt.guatemarket.sistema.ventas.dao.ClienteDAO;
import gt.guatemarket.sistema.ventas.dao.ClienteDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.Categoria;
import gt.guatemarket.sistema.ventas.dao.CategoriaDAO;
import gt.guatemarket.sistema.ventas.dao.CategoriaDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.Producto;
import gt.guatemarket.sistema.ventas.dao.ProductoDAO;
import gt.guatemarket.sistema.ventas.dao.ProductoDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.Venta;
import gt.guatemarket.sistema.ventas.dao.VentaDAO;
import gt.guatemarket.sistema.ventas.dao.VentaDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.DetalleVenta;
import gt.guatemarket.sistema.ventas.dao.DetalleVentaDAO;
import gt.guatemarket.sistema.ventas.dao.DetalleVentaDAOImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author omary
 */
public class FrmVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();

        catalogo.getColumnModel().getColumn(3).setMinWidth(0);
        catalogo.getColumnModel().getColumn(3).setMaxWidth(0);
        catalogo.getColumnModel().getColumn(3).setPreferredWidth(0);

        productosVenta.getColumnModel().getColumn(0).setMinWidth(0);
        productosVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        productosVenta.getColumnModel().getColumn(0).setPreferredWidth(0);

        idVenta.setEditable(false);
        dpiCliente.setEditable(false);
        nitCliente.setEditable(false);
        telefonoCliente.setEditable(false);
        correoCliente.setEditable(false);
        direccionCliente.setEditable(false);

        cargarIdVenta();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void cargarCategorias() {

        CategoriaDAO dao = new CategoriaDAOImpl();

        List<Categoria> categorias = dao.listar();

        categoria.removeAllItems();

        for (Categoria cat : categorias) {
            categoria.addItem(cat.getNombreCategoria());
        }
    }

    private void cargarIdVenta() {

        String sql = "SELECT COALESCE(MAX(idventa), 0) + 1 AS siguiente FROM ventas";

        try (Connection cn = ConexionBD.conectar(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            if (rs.next()) {
                idVenta.setText(rs.getString("siguiente"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al obtener el ID de venta: " + e.getMessage()
            );
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosVenta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        dpiCliente = new javax.swing.JTextField();
        nitCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telefonoCliente = new javax.swing.JTextField();
        correoCliente = new javax.swing.JTextField();
        buscarClientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        catalogo = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        direccionCliente = new javax.swing.JTextField();
        limpiarCampos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idVenta = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Registro Ventas");

        jLabel2.setText("Fecha Venta:");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel4.setText("🔍");

        productosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDProducto", "Cantidad", "Nombre Producto", "Precio Unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productosVenta);

        jLabel3.setText("DPI:");

        jLabel5.setText("NIT:");

        jLabel7.setText("Telefono:");

        jLabel8.setText("Correo:");

        buscarClientes.setText("Buscar");
        buscarClientes.addActionListener(this::buscarClientesActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Catalogo:");

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoria.addActionListener(this::categoriaActionPerformed);

        catalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Producto", "Stocks", "Precio", "IDProducto"
            }
        ));
        jScrollPane2.setViewportView(catalogo);

        jLabel9.setText("Direccion:");

        limpiarCampos.setText("Limpiar");
        limpiarCampos.addActionListener(this::limpiarCamposActionPerformed);

        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Confirmar Venta");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel10.setText("ID:");

        idVenta.addActionListener(this::idVentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7))
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(dpiCliente)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(nitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(direccionCliente)
                                                .addComponent(telefonoCliente)
                                                .addComponent(correoCliente)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(limpiarCampos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dpiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(nitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiarCampos)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClientesActionPerformed
        String nombre = nombreCliente.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el nombre del cliente.");
            return;
        }

        ClienteDAO dao = new ClienteDAOImpl();

        Cliente cliente = dao.buscarPorNombre(nombre);

        if (cliente == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el cliente.",
                    "Cliente no encontrado",
                    JOptionPane.WARNING_MESSAGE);

            return;
        }

        dpiCliente.setText(cliente.getDpi());
        nitCliente.setText(cliente.getNit());
        telefonoCliente.setText(cliente.getTelefono());
        correoCliente.setText(cliente.getCorreo());
        direccionCliente.setText(cliente.getDireccion());
    }//GEN-LAST:event_buscarClientesActionPerformed

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
        nombreCliente.setText("");
        dpiCliente.setText("");
        nitCliente.setText("");
        telefonoCliente.setText("");
        correoCliente.setText("");
        direccionCliente.setText("");
    }//GEN-LAST:event_limpiarCamposActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        String nombreCategoria = (String) categoria.getSelectedItem();

        if (nombreCategoria == null) {
            return;
        }

        CategoriaDAO categoriaDAO = new CategoriaDAOImpl();

        List<Categoria> categorias = categoriaDAO.listar();

        String idCategoria = null;

        for (Categoria cat : categorias) {
            if (cat.getNombreCategoria().equals(nombreCategoria)) {
                idCategoria = cat.getIdCategoria();
                break;
            }
        }

        if (idCategoria == null) {
            return;
        }

        ProductoDAO dao = new ProductoDAOImpl();

        List<Producto> productos = dao.listarPorCategoria(idCategoria);

        DefaultTableModel modelo = (DefaultTableModel) catalogo.getModel();

        modelo.setRowCount(0);

        for (Producto producto : productos) {

            modelo.addRow(new Object[]{
                producto.getNombreProducto(),
                producto.getStock(),
                producto.getPrecio(),
                producto.getIdProducto()
            });
        }
    }//GEN-LAST:event_categoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = catalogo.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un producto de la tabla."
            );
            return;
        }

        String idProducto = catalogo.getValueAt(fila, 3).toString();
        String nombre = catalogo.getValueAt(fila, 0).toString();
        int stock = Integer.parseInt(
                catalogo.getValueAt(fila, 1).toString()
        );
        double precio = Double.parseDouble(
                catalogo.getValueAt(fila, 2).toString()
        );

        String cantidadTexto = JOptionPane.showInputDialog(
                this,
                "Ingrese la cantidad de " + nombre + ":"
        );

        if (cantidadTexto == null) {
            return;
        }

        try {

            int cantidad = Integer.parseInt(cantidadTexto);

            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "La cantidad debe ser mayor a 0."
                );
                return;
            }

            if (cantidad > stock) {
                JOptionPane.showMessageDialog(
                        this,
                        "No hay suficiente stock.\nStock disponible: " + stock
                );
                return;
            }

            double total = cantidad * precio;

            DefaultTableModel modeloVenta
                    = (DefaultTableModel) productosVenta.getModel();

            modeloVenta.addRow(new Object[]{
                idProducto,
                cantidad,
                nombre,
                precio,
                total
            });

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una cantidad válida."
            );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVentaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (nombreCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
            return;
        }
        if (productosVenta.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto.");
            return;
        }
        Venta venta = new Venta();
        venta.setNombre(nombreCliente.getText().trim());
        venta.setDpi(dpiCliente.getText().trim());
        venta.setNit(nitCliente.getText().trim());
        venta.setTelefono(telefonoCliente.getText().trim());
        venta.setCorreo(correoCliente.getText().trim());
        venta.setDireccion(direccionCliente.getText().trim());
        venta.setFechaVenta(java.time.LocalDate.now().toString());
        VentaDAO ventaDAO = new VentaDAOImpl();
        String idVenta = ventaDAO.guardar(venta);
        if (idVenta == null) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la venta.");
            return;
        }
        DetalleVentaDAO detalleDAO = new DetalleVentaDAOImpl();
        for (int i = 0; i < productosVenta.getRowCount(); i++) {
            DetalleVenta detalle = new DetalleVenta();
            detalle.setIdVenta(idVenta);
            detalle.setIdProducto(productosVenta.getValueAt(i, 0).toString());
            detalle.setCantidadProducto(Integer.parseInt(productosVenta.getValueAt(i, 1).toString()));
            detalle.setNombreProducto(productosVenta.getValueAt(i, 2).toString());
            detalle.setPrecioUnitario(Double.parseDouble(productosVenta.getValueAt(i, 3).toString()));
            detalle.setTotal(Double.parseDouble(productosVenta.getValueAt(i, 4).toString()));
            boolean guardado = detalleDAO.guardar(detalle);
            if (!guardado) {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el detalle del producto:\n" + detalle.getNombreProducto());
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Venta guardada correctamente.");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarClientes;
    private javax.swing.JTable catalogo;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JTextField direccionCliente;
    private javax.swing.JTextField dpiCliente;
    private javax.swing.JTextField idVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JTextField nitCliente;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTable productosVenta;
    private javax.swing.JTextField telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
