/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.config.ConexionBD;
import gt.guatemarket.sistema.ventas.dao.ConsultaDespachoDAO;
import gt.guatemarket.sistema.ventas.dao.ConsultaDespachoDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.ConsultaDespacho;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omary
 */
public class HistorialDespachos extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistorialDespachos
     */
    public HistorialDespachos() {
        initComponents();
        setTitle("Reporte Despachos");
        tablaDespachos.getColumnModel().getColumn(1).setMinWidth(0);
        tablaDespachos.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaDespachos.getColumnModel().getColumn(1).setPreferredWidth(0);

        cargarDespachos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDespachos = new javax.swing.JTable();
        verDetalle = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Historial Despachos:");

        tablaDespachos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Despacho", "ID Venta", "Fecha Despacho", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaDespachos);

        verDetalle.setText("Ver Detalle");
        verDetalle.addActionListener(this::verDetalleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verDetalle)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(verDetalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verDetalleActionPerformed

    private void cargarDespachos() {
        ConsultaDespachoDAO dao = new ConsultaDespachoDAOImpl();
        List<ConsultaDespacho> despachos = dao.listar();
        DefaultTableModel modelo = (DefaultTableModel) tablaDespachos.getModel();
        modelo.setRowCount(0);
        for (ConsultaDespacho despacho : despachos) {
            modelo.addRow(new Object[]{despacho.getIdDespacho(), despacho.getIdVenta(), despacho.getFechaDespacho(), despacho.getEstadoDespacho()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDespachos;
    private javax.swing.JButton verDetalle;
    // End of variables declaration//GEN-END:variables
}
