/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gt.guatemarket.sistema.ventas.vista;

import gt.guatemarket.sistema.ventas.dao.ConsultaVentaDAO;
import gt.guatemarket.sistema.ventas.dao.ConsultaVentaDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.ConsultaVenta;
import gt.guatemarket.sistema.ventas.dao.DetalleVentaDAO;
import gt.guatemarket.sistema.ventas.dao.DetalleVentaDAOImpl;
import gt.guatemarket.sistema.ventas.modelo.DetalleConsultaVenta;
import java.util.List;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omary
 */
public class HistorialVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistorialVentas
     */
    public HistorialVentas() {
        initComponents();
        setTitle("Reporte Ventas");
        cargarVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        verDetalles = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Historial Ventas:");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Venta", "Nombre Cliente", "Fecha Venta", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        verDetalles.setText("Ver Detalle");
        verDetalles.addActionListener(this::verDetallesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verDetalles)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(verDetalles)
                        .addGap(3, 3, 3)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarVentas() {
        ConsultaVentaDAO dao = new ConsultaVentaDAOImpl();
        List<ConsultaVenta> ventas = dao.listar();
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        modelo.setRowCount(0);
        for (ConsultaVenta venta : ventas) {
            modelo.addRow(new Object[]{venta.getIdVenta(), venta.getNombreCliente(), venta.getFechaVenta(), venta.getTotal()});
        }
    }

    private void verDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetallesActionPerformed
        int fila = tablaVentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una venta de la tabla.");
            return;
        }
        String idVenta = tablaVentas.getValueAt(fila, 0).toString();
        DetalleVentaDAO dao = new DetalleVentaDAOImpl();
        List<DetalleConsultaVenta> detalles = dao.listarPorVenta(idVenta);
        if (detalles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Esta venta no tiene detalles.");
            return;
        }
        String[] columnas = {"Nombre Producto", "Cantidad", "Precio Unitario", "Total"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (DetalleConsultaVenta detalle : detalles) {
            modelo.addRow(new Object[]{detalle.getNombreProducto(), detalle.getCantidad(), detalle.getPrecioUnitario(), detalle.getTotal()});
        }
        JTable tablaDetalle = new JTable(modelo);
        JScrollPane scroll = new JScrollPane(tablaDetalle);
        JOptionPane.showMessageDialog(this, scroll, "Detalle de Venta #" + idVenta, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_verDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JButton verDetalles;
    // End of variables declaration//GEN-END:variables
}
